Projects/App/Sources/Intro/IntroFeature.swift
Projects/App/Sources/Intro/IntroView.swift
Projects/Feature/FeatureLogin/Sources/LoginRoot/LoginRootFeature.swift

> #62 
- 테스트 플라이트로 어플을 받았을 시에, 로그인에서 메인으로 넘어가는 상황에서 앱 충돌이 일어나는 것을 해결하고자 하였습니다.
>
- 로그인 화면을 구현할 당시 FullScreenCover로 사용될 것을 염두하고 `dismiss`코드를 넣었던게 원인이지 않았을까 하여 해당 코드를 제거하였습니다.
- 시뮬레이터, 로컬 빌드 설치에는 충돌이 안일어나서 이번 pr을 머지하고 결과를 확인해볼 예정입니다.
close #62

HotFix: 앱 충돌 수정

---

.gitignore
Projects/Feature/FeaturePokit/Sources/PokitRootView.swift

> #62 
- 릴리즈 빌드에서 일어나는 충돌을 해결하였습니다.
- 참고로, 하는김에 환경변수를 담은 파일의 gitignore도 처리하였습니다.
>
xcode에서 release모드로 빌드하고 디버깅을 하면서 아래와 같은 문구를 마주쳤습니다.
```
failed to demangle witness for associated type 'Body' in conformance 'FeaturePokit.PokitRootView: View' 
from mangled name '\233' - subject type x does not conform to protocol Equatable
```
swiftui view의 body에 equatable 프로토콜을 준수해야하는 친구가 있는데, 준수를 하지 않아서 나오는 문구였고, 이 문구와 동시에 앱이 튕겼습니다.(왜 이게 런타임에러;;)
그래서 코드를 찾아본 결과 tca의 `IdentifiedArrayOf`타입을 가진 배열이 `animation`모디파이어의 value값으로 쓰이는 것을 발견했고, 해당 코드를 지우니 마법같이 충돌이 해결되었습니다
```swift
@Reducer
public struct PokitRootFeature {
@ObservableState
public struct State: Equatable {
...
var mock: IdentifiedArrayOf<PokitRootCardMock> = []
var …
```

Hotfix: 앱 충돌 해결

---

Projects/CoreKit/Sources/CoreNetwork/MoyaProvider+request.swift
Projects/CoreKit/Sources/Data/DTO/Base/BasePageableRequest.swift
Projects/CoreKit/Sources/Data/DTO/Category/CategoryEditRequest.swift
Projects/CoreKit/Sources/Data/Network/Category/CategoryClient.swift
Projects/CoreKit/Sources/Data/Network/Category/CategoryEndpoint.swift
Projects/Domain/Sources/CategoryDetail/CategoryDetail.swift
Projects/Domain/Sources/Pokit/Pokit.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingFeature.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingView.swift
Projects/Feature/FeatureLogin/Sources/LoginRoot/LoginRootFeature.swift
Projects/Feature/FeatureLogin/Sources/RegisterNickname/RegisterNicknameFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootView.swift

#76 
- 포킷 플로우에서 카테고리 관련된 모든 API를 연결했습니다.
미분류 카테고리 조회는 서버쪽 작업중이라 아직 미완이고, 링크 추가 / 수정에서의 카테고리 추가 기능같은 경우에는 도형님 작업하실 때 겹쳐지는 화면이다보니 조율이 필요할 것 같아 일단 남겨두겠습니다.
- Response body가 없는 경우가 있더라구요. 제가 깜빡하고 작업을 하지 않아 MoyaProvider+request에 해당 함수 추가해두었습니다.
>
도메인쪽 연결을 잘 사용하고 있는지 따끔하게 혼내주세요~~
close #76

feat: Pokit Flow API Connect

---

.gitignore
Makefile
Projects/App/Project.swift
Projects/App/Resources/Pokit-info.plist
Projects/App/Sources/MainTab/MainTabFeature.swift
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/App/Sources/Root/RootFeature.swift
Projects/CoreKit/Project.swift
Projects/CoreKit/Sources/Data/Client/Keychain/KeychainClient.swift
Projects/CoreKit/Sources/Data/Client/SocialLogin/Controller/AppleLoginController.swift
Projects/CoreKit/Sources/Data/Client/SocialLogin/Controller/GoogleLoginController.swift
Projects/CoreKit/Sources/Data/Client/SocialLogin/Model/SocialLoginInfo.swift
Projects/CoreKit/Sources/Data/Client/UserDefaults/UserDefaultsKey.swift
Projects/CoreKit/Sources/Data/DTO/Auth/AppleTokenRequest.swift
Projects/CoreKit/Sources/Data/DTO/Auth/AppleTokenResponse.swift
Projects/CoreKit/Sources/Data/DTO/Auth/WithdrawRequest.swift
Projects/CoreKit/Sources/Data/DTO/User/NicknameEditRequest.swift
Projects/CoreKit/Sources/Data/Network/Auth/AuthClient.swift
Projects/CoreKit/Sources/Data/Network/Auth/AuthEndpoint.swift
Projects/Feature/FeatureLogin/Sources/LoginRoot/LoginRootFeature.swift
Projects/Feature/FeatureLogin/Sources/RegisterNickname/RegisterNicknameFeature.swift
Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingFeature.swift
Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingView.swift
Projects/Feature/FeatureSetting/Sources/Setting/PokitSettingFeature.swift
Projects/Util/Sources/Constants.swift
Tuist/Package.swift

#84
설정창 관련한 API 및 화면연결 작업을 했습니다.
- 닉네임 수정 API 연결
- 회원탈퇴 API 연결
공통: 구글 / 애플 로그인의 회원탈퇴 로직을 추가했습니다. 
애플 회원탈퇴를 위해 애플서버로 직접 요청하는 로직을 추가했습니다. 
이를 위해 Team ID, Key ID, p8파일 등이 필요했으며, 이를 Private Repository로부터 받아옵니다. 기존과 동일하게 `Secret.xcconfig`파일에서 ID값들을 확인할 수 있으며, CoreKit에서도 사용이 되도록 configuration을 수정했습니다.
또한 p8파일도 CoreKit의 Resources에서 관리가 필요할 것 같아 세팅을 수정했습니다.
- 이 외 링크로 이동되는 화면들 연결작업
close #84

feat: Setting Flow API Connect

---

Projects/CoreKit/Sources/Data/DTO/Category/BaseCategoryResponse.swift
Projects/CoreKit/Sources/Data/DTO/Category/CategoryEditResponse.swift
Projects/CoreKit/Sources/Data/DTO/Category/CategoryListInquiryResponse.swift
Projects/CoreKit/Sources/Data/DTO/Content/ContentDetailResponse.swift
Projects/DSKit/Project.swift
Projects/DSKit/Sources/Components/PokitCard.swift
Projects/DSKit/Sources/Components/PokitLinkCard.swift
Projects/Domain/Sources/Base/BaseCategoryItem.swift
Projects/Domain/Sources/Base/BaseContentDetail.swift
Projects/Domain/Sources/ContentSetting/ContentSetting.swift
Projects/Domain/Sources/DTO/Category/CategoryListInquiryResponse+Extention.swift
Projects/Domain/Sources/DTO/Content/ContentDetailResponse+Extension.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
Projects/Feature/FeatureCategoryDetail/Sources/Sheet/CategoryFilterSheet.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingFeature.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingView.swift
Projects/Feature/FeatureCategorySetting/Sources/Sheet/ProfileBottomSheet.swift
Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
Projects/Feature/FeatureLogin/Sources/RegisterNickname/RegisterNicknameFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingFeature.swift
Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingView.swift
Projects/Util/Sources/Extension/String+Extension.swift
Tuist/Package.swift

#92 
QA 수정사항입니다.
- 정렬 최신순 수정
- 카테고리상세 필터 고장 수정
- 이미지캐싱 (AsyncImage -> Nuke)
- 프로필선택 default Image Pokie로 수정
- 이미지 선택 시 이전에 선택한 이미지 테두리 추가
- 링크 추가 시 카테고리 목록에 미분류 최상단에 위치하게 추가
- 닉네임 특수문자 에러처리 수정
- 닉네임 처리 debounce 3sec -> 0.5 sec 
지금까지 나온것중에 하나빼고 다 수정했습니다.
컨텐츠 상세에서삭제 수정 시 이전화면에 반영되게 하는 흐름은 저번에 한번 설명드렸던 것 같아요. 이부분은 좀 얘기를 나눠야 할 것 같기 때문에 내일 만나서 같이 해보면 좋을 것 같습니다.

fix: QA 반영(08.16)

---

Projects/App/Sources/AppDelegate/AppDelegate.swift
Projects/App/Sources/AppDelegate/AppDelegateFeature.swift
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/App/Sources/PokitApp.swift
Projects/App/Sources/Root/RootFeature.swift
Projects/App/Sources/Root/RootView.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
Projects/Feature/FeatureSetting/Sources/Search/PokitSearchFeature.swift
Projects/Feature/FeatureSetting/Sources/Search/PokitSearchView.swift

> #98 
- ContentDetail에 `dismiss` 발동될 시점의 `delegate` 연결
- ContentSetting에 `저장하기_완료` 발동될 시점의 `delegate` 연결
- @stealmh RootFeature의 store 관리를 개선해 주셨습니다.
- 로그아웃, 회원탈퇴도 그렇고, 이번 ContentDetail 쪽 작업을 하면서 아래와 같은 경고문을 마주하였습니다.
```
An "ifLet" at "App/MainTabFeature.swift:113" received a presentation action when destination state was absent. …
Action:
MainTabFeature.Action.contentDetail(.presented(.delegate(.컨텐츠_삭제_완료(contentId:))))
This is generally considered an application logic error, and can happen for a few reasons:
• A parent reducer set destination state to "nil" before this reducer ran. This reducer must run before any other reducer sets destination state to "nil". This ensures that destination reducers can handle …
```

부모 <-> 자식 뷰 간 필요한 delegate 정의

---

Projects/App/Sources/MainTab/MainTabFeatureView.swift
Projects/DSKit/Sources/Components/PokitHeader.swift
Projects/DSKit/Sources/Components/PokitHeaderItems.swift
Projects/DSKit/Sources/Modifiers/PokitNavigationBarModifier.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingView.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListView.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
Projects/Feature/FeatureLogin/Sources/AgreeToTerms/AgreeToTermsView.swift
Projects/Feature/FeatureLogin/Sources/LoginRoot/LoginRootView.swift
Projects/Feature/FeatureLogin/Sources/RegisterNickname/RegisterNicknameView.swift
Projects/Feature/FeatureLogin/Sources/SelectField/SelectFieldView.swift
Projects/Feature/FeatureLogin/Sources/SignUpDone/SignUpDoneView.swift
Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
Projects/Feature/FeatureSetting/Sources/Alert/PokitAlertBoxView.swift
Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingView.swift
Projects/Feature/FeatureSetting/Sources/Setting/PokitSettingView.swift

> #92 
- 디자이너 요청에 따라 커스텀 네비게이션 바로 전환했습니다. (죄송합니다..ㅎㅎ)
- `PokitHeader`, `PokitHeaderItems`를 추가하였습니다.
- `.navigationBar`모디파이어를 새롭게 바꿨습니다.
>
- 사용방법
```swift
...
.pokitNavigationBar {
PokitHeader {
PokitHeaderItems(placement: .leading) {
PokitToolbarButton(.icon(.arrowLeft)) {
send(.backButtonTapped)
}
}
}
}
...
```
- 내부적으로 `VStack`으로 구현되었기 때문에 해당하는 화면의 최상단에 써야합니다!
```swift
...
func body(content: Content) -> some View {
VStack(spacing: 0) {
header
content
}
.navigationBarBackButtonHidden()
.background(.pokit(.bg(.base)))
}
...
```
close 이슈번호

QA: 커스텀 네비게이션 바 전환

---

Projects/Domain/Sources/Base/BaseCategoryItem.swift
Projects/Domain/Sources/Base/BaseCategoryListInquiry.swift
Projects/Domain/Sources/Base/BaseContentItem.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Util/Sources/Extension/Array+Sortable.swift
Projects/Util/Sources/Extension/DateFormat.swift
Projects/Util/Sources/Protocols/Sortable.swift

#92
- 정렬이 적용이 안되던 버그를 수정
기존의 정렬은 createdAt이라는 String값을 서버로부터 받아와 이를 토대로 정렬을 돌렸었는데, 
정렬이 되는것처럼 보여도 프린트 찍어서 확인해보니 순서가 엉망이였습니다.
```swift
/// 카테고리 일 때
state.domain.categoryList.data?.sort { $0.createdAt < $1.createdAt }
/// 미분류 카테고리 일 때
state.domain.unclassifiedContentList.data?.sort { $0.createdAt < $1.createdAt }
```
이는 String값만으로 sort를 진행하기 때문에 정확도가 많이 떨어지는 방식이였습니다.
String값을 Date로 변환하고 이를 근거로 정렬을 수행하고자 하였습니다.
DateFormatter를 생성하는 것은 생각보다 비용이 많이 드는 작업에 속합니다. 
그렇기 때문에 이곳저곳에서 인스턴스를 만들고 버리는 것 보다는 단일 인스턴스를 캐시화 하는 것이 효율적입니다.
```swift
public enum DateFormat: String {
/// 포맷형식: yyyy-MM-dd
case yearMonthDate = "yyyy.MM.dd"
}
extension DateFormat {
public var formatter: DateFormatter {
guard let fmt = DateFormat.cachedFormatters[self] else {
let generatedFormatter = …
```

fix: 최신순 정렬 수정

---

Projects/App/Sources/MainTab/MainTabPath.swift
Projects/CoreKit/Sources/Data/Client/SwiftSoupClient/SwiftSoupClient.swift
Projects/CoreKit/Sources/Data/DTO/Base/BaseUserResponse.swift
Projects/CoreKit/Sources/Data/DTO/Base/ContentBaseResponse.swift
Projects/CoreKit/Sources/Data/Network/Content/ContentClient.swift
Projects/CoreKit/Sources/Data/Network/Remind/RemindEndpoint.swift
Projects/CoreKit/Sources/Data/Network/User/UserClient.swift
Projects/CoreKit/Sources/Data/Network/User/UserEndpoint.swift
Projects/DSKit/Sources/Components/PokitLinkCard.swift
Projects/Domain/Sources/Base/BaseContentItem.swift
Projects/Domain/Sources/Base/BaseUser.swift
Projects/Domain/Sources/ContentList/ContentList.swift
Projects/Domain/Sources/DTO/User/BaseUserResponse+Extension.swift
Projects/Domain/Sources/NicknameSetting/NicknameSetting.swift
Projects/Domain/Sources/Pokit/Pokit.swift
Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListFeature.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListView.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootType.swift
Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingFeature.swift
Projects/Feature/FeatureSetting/Sources/Setting/NickNameSetting/NickNameSettingView.swift
Projects/Util/Sources/Protocols/PokitLinkCardItem.swift

> #92 
- 미분류 컨텐츠 목록 정렬 버튼 이름순 -> 오래된순 이름으로 변경
- 즐겨찾기 해제 api response 처리 수정
- 안읽음, 즐겨찾기 컨텐츠 목록 정렬 기능 추가
- 안읽음, 즐겨찾기 컨텐츠 목록 페이지네이션 기능 추가
- 컨텐츠 수정/추가에서 메모 100자 넘어갈 시 저장버튼 비활성화
- 미분류 <-> 포킷 전환시 포킷 목록 조회 추가
- 닉네임 수정 시 사용자 닉네임 텍스트 필드에 반영 추가
- 링크 추가 화면에서 복사한 링크 자동입력 -> 팝업 노출로 변경
- 링크 추가/수정 시 링크에 대한 제목 파싱 실패 시 링크 미리보기에 "제목을 입력해주세요" 문구 삽입
>
- 정렬 관련해서 구체적인 기획이 정해짐에 따라, PokitFeature에서 정렬 로직을 변경하였습니다. 목록이 초기화 되는 시점은 포킷 <-> 미분류 전환, 정렬 버튼 클릭 2가지 경우입니다.
- 정렬 로직을 변경한 후, 목록들을 갱신하는 시점에서 뷰를 업데이트 하면서, 뷰의 계층, 애니메이션 처리 등으로 인하여, ui 성능이 심각하게 하락하는 현상이 있었습니다. 때문에, 전환 애니메이션과, PokitRootView의 뷰 계층을 수정하였습니다.
- 닉네임 조회를 구현하면서, 한글로 되어 있지만 자음과 모음이 분리된 닉네임(ex: ㄱㅣㅁㄷㅗㅎㅕㅇ)은 올바르지 않은 닉네임이라고 뜨는데, 의도하신건지 궁금합니다!(그래서 건들지 않았음)
close 이슈번호

Fix: PM의 QA 반영

---

Projects/Feature/FeatureContentList/Sources/ContentList/ContentListFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift

fix: 페이지네이션 수정

---

Projects/App/Sources/MainTab/MainTabFeature.swift
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingFeature.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift

#111
링크 추가 화면에서 카테고리를 추가한 후 이전 화면으로 돌아오면 등록한 카테고리가 적용될 수 있게 수정했습니다.
>

fix: 카테고리 추가 후 링크 추가 및 수정화면 반영

---

Projects/App/Resources/Pokit-info.plist
Projects/App/Sources/AppDelegate/AppDelegateFeature.swift
Projects/App/Sources/Intro/IntroFeature.swift
Projects/App/Sources/MainTab/MainTabFeature.swift
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/CoreKit/Sources/Data/Client/UserDefaults/UserDefaultsKey.swift

#111
푸시알람을 통해 앱을 진입하는 경우의 분기처리를 추가했습니다.
- 앱을 사용중일 때 푸시알람이 오는경우
- 앱을 미사용중일 때 푸시알람이 오는경우
분기처리는 MainTabFeature에서 담당하게 됩니다.
```swift
@Shared(.inMemory("PushTapped")) var isPushTapped: Bool = false
```
TCA의 Shared를 통해 이를 쉽게 관리 할 수 있습니다. 해당 프로퍼티는 총 2가지의 파일에서 추적합니다. 
:: `AppDelegateFeature`, `MainTabFeature`
```swift
case let .userNotifications(.didReceiveResponse(_, completionHandler)):
state.isPushTapped = true
return .run { @MainActor _ in completionHandler() }
```
푸시를 누르면 isPushTapped의 값을 true로 바꿉니다. 
Shared의 option을 inMemory로 설정했기 때문에 앱이 실행되는 순간에만 값이 남아있습니다.
당연하게도 `PushTapped`라는 키값을 두 가지 파일에서 같이 사용하고 있기 때문에 flag가 바뀐 것을 MainTabFeature도 알아차릴 수 있습니다.
```swift
case .onAppear:
if state.isPushTapped {
return .send(.pushAlertTapped(true))
}
return .merge(
.run { send in
// ...
},
.publisher { …
```

fix: fcm 분기처리 수정

---

Projects/App/Sources/Intro/IntroFeature.swift
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/CoreKit/Sources/Data/DTO/Auth/WithdrawRequest.swift
Projects/DSKit/Sources/Components/PokitShareSheet.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListFeature.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListView.swift
Projects/Feature/FeatureLogin/Sources/Login/LoginFeature.swift
Projects/Feature/FeatureLogin/Sources/Login/LoginView.swift
Projects/Feature/FeatureLogin/Sources/LoginRoot/LoginRootFeature.swift
Projects/Feature/FeatureLogin/Sources/LoginRoot/LoginRootView.swift
Projects/Feature/FeatureLogin/Sources/SelectField/SelectFieldFeature.swift
Projects/Feature/FeatureLogin/Sources/SignUpDone/SignUpDoneFeature.swift
Projects/Feature/FeatureLogin/Sources/SignUpDone/SignUpDoneView.swift
Projects/Feature/FeatureLoginDemo/Sources/FeatureLoginDemoApp.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
Projects/Feature/FeatureSetting/Sources/Search/PokitSearchFeature.swift
Projects/Feature/FeatureSetting/Sources/Search/PokitSearchView.swift
Projects/Feature/FeatureSetting/Sources/Setting/PokitSettingFeature.swift

> #111 
- 컨텐츠 상세에서, 즐겨찾기와 컨텐츠 조회 액션이 발생했을 시, 부모 뷰 에게 전달하는 시점을 변경하였습니다.
- 컨텐츠 공유로 공유 시트를 띄웠을 시에 공유시트의 닫기 버튼을 눌렀을 시에 닫히지 않는 문제를 수정하였습니다.
- 구글 로그인 회원 탈퇴 시 우리 서버로 탈퇴 요청이 실행되지 않는 문제를 수정하였습니다.
- 회원가입 완료 시 뒤로가기 버튼을 없애기 위해 `LoginRootFeature`를 `LoginFeature` <-> `SignUpFeature` 간 `ifCaseLet` 처리로 바꿨습니다.
>
- 앱 멈춤 현상을 해결하기 위해 컨텐츠 상세에서 부모 뷰에 액션 전달 시점을 바꿔보았지만, `ifLet`오류만 사라졌을 뿐 증상은 동일하였습니다. (제 생각에는 TCA의 고질적 문제가 아닐까...)
- 어쩌다 보니 구글로그인 회원탈퇴가 안되는 것을 발견하여 해결하였습니다. (안고치기엔 너무 치명적인거 같았어요)
- 회원 탈퇴 고치면서 회원가입 완료 화면에 뒤로가기를 비활성화 하였습니다.
- 굳이 굳이 힘들게 `ifCaseLet`로 바꾼 이유는 저희가 뒤로가기 버튼을 커스텀 하면서, 뒤로가기 제스처를 강제로 활성화 시켰기 때문입니다. 이로 인해 버튼이 안보여도 뒤로가기가 가능해지는 문제를 보였고, 아예 화면 플로우를 자체를 분리 시켰습니다.
- `ifCaseLet` 처리를 하다가 문득 든 생각은.. Pokit <-> Remind 화면간 전환에 …

1.0.0에서 발견한 버그 수정

---

Projects/App/Resources/Pokit-info.plist
Projects/App/Sources/MainTab/MainTabFeature.swift
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingFeature.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingView.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
Tuist/Package.swift

#120
- 1.0.3 버전 수정 및 tca 버전 고정
- Perception Tracking 경고 수정
CategorySetting에서 발생하는 Perception Tracking은 총 2가지 케이스입니다.
1. Lazy한 View에 WithPerceptionTracking을 붙이지 않았을 때
2. ifLet
1번의 경우 클로저 뷰에 Perception을 감싸는 것으로 해결되었습니다.
2번의 경우 링크 추가 / 수정화면으로 이동된 후 contentDetail을 dismiss하고 있어서, 즉 순서가 바뀌었기 때문에 발생
`as is`: 링크추가수정화면 나타남 -> 화면에 컨텐츠상세 시트가 없는데 dismiss action 발생함 -> ??
`to be`: 시트 내림(nil) -> 링크 추가 수정화면 나타남
<br>
- 링크 수정에서 카테고리를 추가하고 돌아오면 적용이 안되는 버그 수정
작업하면서 알게 된 사실인데 링크 추가 / 수정 로직을 분리해놓을 필요가 있을 것 같습니다. (거의 엉켜있다시피함)
>

fix: 카테고리 설정 버그 수정

---

Projects/CoreKit/Sources/Data/DTO/Content/ContentCountResponse.swift
Projects/CoreKit/Sources/Data/Network/Remind/RemindClient.swift
Projects/CoreKit/Sources/Data/Network/Remind/RemindEndpoint.swift
Projects/Domain/Sources/ContentList/ContentList.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListFeature.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListView.swift

> #120 
- ContentList에서 컨텐츠 개수가 잘못나오는 현상을 수정하였습니다.
- ContentListFeature에서 안쓰이는 액션을 제거하였습니다.
>
- 이정도 까지 하고 1.0.3 배포하는게 어떤지..궁금합니다! 나머지 멈추는 현상은 장기적으로 가져가는게 어떨지..(생각보다 앱 사용에 불편함이 없기도 하고, tca 자체를 더 깊게 파아햘것 같다는 생각입니다...)

ContentList 컨텐츠 갯수 수정

---

Projects/App/Resources/Pokit-info.plist
Projects/App/Sources/MainTab/MainTabFeatureView.swift
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift

> #129 
- Remind에 대한 액션들을 한글화 하였습니다.
- 위임 받은 액션은 `DelegateAction`이 아닌 `ScopeAction`으로 이동하였습니다.
>
- 컨벤션에 맞춰 한글화 진행하였는데 피드백 부탁드립니다.
- `ScopeAction`에 대해 조금 생각을 해보았습니다. 어느 순간 부터 `ScopeAction`을 안쓰게 되어 버리기도 했고, `DelegateAction`은 위임의 역할만 해야 하는데, 제가 아무 생각없이 액션에 대한 코드 수행을 넣고 있어서.. 명확하게 할 필요가 있다 생각했습니다.
close 이슈번호

Remind 리펙토링

---

Projects/CoreKit/Sources/Data/Client/SwiftSoupClient/SwiftSoupClient+TestKey.swift

> ex) #이슈번호, #이슈번호
#137 
- `DependencyMacro` 도입 후 컴파일 충둘문제 수정
>
- 저는 보통 저렇게 긴 에러로그는 GPT한테 해석시키는데, GPT가 `SwiftSoupClient`의 `DependencyKey` 관련 오류라고 언급을 해주었습니다.
- 그래서 코드를 보니 아래와 같은 코드에서 오류가 난것으로 보였습니다.
```swift
public static let previewValue = liveValue
```
- 제 생각에는 `TestDependencyKey` 프로토콜 채용 부분에 `liveValue`를 바로 호출한게 문제가 된거 같은데, 기존에는 문제 없다가 `DependencyMacro`를 도입하면서 문제가 발생한 원인을 모르겠습니다. 원인을 알고 계시다면 설명 부탁드리겠습니다!
- 혹시나 작업하시는데 문제 없었으면 `DependencyMacro`와 xcode 16의 콜라보라 추측이 됩니다...(실제로 CI/CD 워크플로우의 xcode를 16으로 올렸더니 동일한 문제가 발생했음)
close #137

fix: DependencyMacro 도입 후 컴파일 충둘문제 수정

---

Projects/Feature/FeatureLogin/Sources/AgreeToTerms/AgreeToTermsFeature.swift
Projects/Feature/FeatureLogin/Sources/AgreeToTerms/AgreeToTermsView.swift
Projects/Feature/FeatureLogin/Sources/Login/LoginFeature.swift
Projects/Feature/FeatureLogin/Sources/Login/LoginView.swift
Projects/Feature/FeatureLogin/Sources/RegisterNickname/RegisterNicknameFeature.swift
Projects/Feature/FeatureLogin/Sources/RegisterNickname/RegisterNicknameView.swift
Projects/Feature/FeatureLogin/Sources/SelectField/SelectFieldFeature.swift
Projects/Feature/FeatureLogin/Sources/SignUpDone/SignUpDoneFeature.swift
Projects/Feature/FeatureLogin/Sources/SignUpDone/SignUpDoneView.swift

> #129 
- 로그인 화면 플로우에 해당하는 Feature들에 액션 컨벤션 적용
>
close 이슈번호

refactor: 로그인 플로우 Feature 액션 컨벤션 수정

---

Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift

> #129 
- ContentSettingFeature 액션 컨벤션 적용
>
close 이슈번호

refactor: ContentSettingFeature 액션 컨벤션 수정

---

Projects/Feature/FeatureCategoryDetailTests/Resources/info.plist
Projects/Feature/FeatureCategoryDetailTests/Sources/FeatureCategoryDetailTests.swift
Projects/Feature/FeatureCategorySettingTests/Resources/info.plist
Projects/Feature/FeatureCategorySettingTests/Sources/FeatureCategorySettingTests.swift
Projects/Feature/FeatureCategorySharingTests/Resources/info.plist
Projects/Feature/FeatureCategorySharingTests/Sources/FeatureCategorySharingTests.swift
Projects/Feature/FeatureContentDetailTests/Resources/info.plist
Projects/Feature/FeatureContentDetailTests/Sources/FeatureContentDetailTests.swift
Projects/Feature/FeatureContentListTests/Resources/info.plist
Projects/Feature/FeatureContentListTests/Sources/FeatureContentListTests.swift
Projects/Feature/FeatureContentSettingTests/Resources/info.plist
Projects/Feature/FeatureContentSettingTests/Sources/FeatureContentSettingTests.swift
Projects/Feature/FeatureLoginTests/Resources/info.plist
Projects/Feature/FeatureLoginTests/Sources/FeatureLoginTests.swift
Projects/Feature/FeatureMyFolderTests/Resources/info.plist
Projects/Feature/FeatureMyFolderTests/Sources/FeatureMyFolderTests.swift
Projects/Feature/FeatureMyPageTests/Resources/info.plist
Projects/Feature/FeatureMyPageTests/Sources/FeatureMyPageTests.swift
Projects/Feature/FeaturePokitTests/Resources/info.plist
Projects/Feature/FeaturePokitTests/Sources/FeaturePokitTests.swift
Projects/Feature/FeatureRemindTests/Resources/info.plist
Projects/Feature/FeatureRemindTests/Sources/FeatureRemindTests.swift
Projects/Feature/FeatureSettingTests/Resources/info.plist
Projects/Feature/FeatureSettingTests/Sources/FeatureSettingTests.swift
Projects/Feature/Project.swift
Tuist/ProjectDescriptionHelpers/Feature.swift
Tuist/Templates/test/InfoPlist.stencil
Tuist/Templates/test/Test.stencil
Tuist/Templates/test/test.swift

#144 
유닛테스트 환경을 구성하기 위해 Tuist설정을 일부 작성하였습니다.
App 모듈에 대한 단위테스트 모듈은 만들지 않았습니다 (피쳐들 테스트만해도 어마어마하게 걸릴 것 같아서)
따라서 개별 모듈단위 테스팅이 끝난 후 바텀업 형태로 앱 모듈에 대한 테스팅도 마저 진행 할 예정입니다.
>
close #144

feat: 유닛테스트 작업환경 세팅

---

Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift

> #129 
- ContentDetailFeature 액션 컨벤션 적용
>
close 이슈번호

refactor: ContentDetailFeature 액션 컨벤션 수정

---

Projects/App/Sources/MainTab/MainTabFeatureView.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootView.swift

#129 
- 액션 컨벤션에 맞춰 수정
- 파라미터로 직접넣는 방법에서 미리 선언해 이를 넣어주는 방식으로 일부 액션 수정
>

refactor: PokitFeature 액션 수정

---

Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
Projects/Feature/FeatureCategoryDetail/Sources/Sheet/CategoryFilterSheet.swift

#129
- 액션 컨벤션에 맞춰 수정
- 일부 순서가 중요하지 않은 Effect 일부 수정
- 열거형 case let 수정
```diff
-- case .onAppear:
-- return .run { send in
-- let request = BasePageableRequest(page: 0, size: 30, sort: ["createdAt,desc"])
-- let response = try await categoryClient.카테고리_목록_조회(request, true).toDomain()
-- await send(.async(.카테고리_내_컨텐츠_목록_조회))
-- await send(.inner(.카테고리_목록_조회_결과(response)))
--   for await _ in self.pasteboard.changes() {
--   let url = try await pasteboard.probableWebURL()
--   await send(.delegate(.linkCopyDetected(url)), animation: .pokitSpring)
--   }
--}
++ case .뷰가_나타났을때:
++ return .merge(
++ .send(.async(.카테고리_내_컨텐츠_목록_조회_API)),
++ .send(.async(.카테고리_목록_조회_API)),
++ .send(.async(.클립보드_감지))
++ )
```
예시로 이와 같이 액션으로 분리할 수 있는 것들을 빼낸 후 merge를 통해 가독성을 챙기고
굳이 각기다른 순서가 중요하지 않은 3개의 API들의 await 제거 …

refactor: CategoryDetailFeature 액션 수정

---

Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingFeature.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingView.swift
Projects/Feature/FeatureCategorySetting/Sources/Sheet/ProfileBottomSheet.swift

#129
- 액션 컨벤션에 맞춰 수정
- 프로필 목록, 카테고리 목록 API가 서로 엉켜있어 이를 분리
- 액션으로 가독성을 챙길 수 있는 부분 수정
- 주석들 제거
>

refactor: CategorySettingFeature 액션 수정

---

Projects/Feature/FeatureCategorySharing/Sources/CategorySharing/CategorySharingFeature.swift
Projects/Feature/FeatureCategorySharing/Sources/CategorySharing/CategorySharingView.swift

#129
- 액션 컨벤션에 맞춰 수정
- computedProperty 일부 수정 (get 제거 및 컨벤션에 맞춤)
>

refactor: CategorySharingFeature 액션 수정

---

Projects/App/ShareExtension/Info.plist
Projects/DSKit/Sources/Components/PokitLinkCard.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift

> ex) #이슈번호, #이슈번호
#152 
- 인스타그램 도메인을 가진 url에서 이미지 조회가 안되는 문제를 수정하였습니다.
+++++++++++++++++++++++
- App과 Share Extension의 버전을 맞췄습니다.
>
- 저희는 `Nuke`를 쓰고 있기 때문에, 뷰 단에서 `User-Agent` 헤더 값을 가진 요청을 만들어 `LazyImage`에 주입시켰습니다.
```Swift
@MainActor
private func thumbleNail(url: URL) -> some View {
var request = URLRequest(url: url)
request.setValue(
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36",
forHTTPHeaderField: "User-Agent"
)
return LazyImage(request: .init(urlRequest: request)) { phase in
Group {
if let image = phase.image {
image
.resizable()
.aspectRatio(contentMode: .fill)
} else {
placeholder
}
}
...
```
- 이렇게 `User-Agent`를 설정하게 되면, 해당 서비스에서 일반적인 …

Fix: 인스타그램 등 일부 도메인에서 이미지 조회가 안되는 문제 수정

---

Projects/DSKit/Sources/Components/PokitLinkPreview.swift
Projects/Feature/FeatureSetting/Sources/Alert/PokitAlertBoxView.swift

> ex) #이슈번호, #이슈번호
#158 
- `PokitAlertBoxView`의 알림 목록 empty의 UX 워딩을 수정하였습니다.
- `PokitLinkPreview`에서 기본 이미지가 영역을 벗어나는 현상을 수정하였습니다.
--- | ---
>
- 이거 머지하고 바로 1.0.4 릴리즈 할 예정입니다
- UI 점검하다가 발견했는데.. 포킷 목록이 살짝 위쪽으로 짤린거 같은데 원인을 모르겠어요...
close #158

Fix: UI 피드백 반영

---

Projects/App/Resources/Pokit-info.plist
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/DSKit/Sources/Components/PokitCaution.swift
Projects/DSKit/Sources/Components/PokitList.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
Projects/Feature/FeatureCategorySharing/Sources/CategorySharing/CategorySharingView.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListView.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
Projects/Feature/FeatureSetting/Sources/Alert/PokitAlertBoxView.swift
Projects/Feature/FeatureSetting/Sources/Search/PokitSearchView.swift

#156 
- Empty / Error 화면인 PokitCaution 내부 프로퍼티를 열거형으로 합쳤습니다. 이곳저곳에서 하드코딩된 string값이 사용되고 있기에 유지보수 차원에서 이번 작업과 함께 수정했습니다.
- empty 시 카테고리추가 / 링크추가 액션들의 화면이동 로직을 연결했습니다.
- 검색바 placeholder 수정
포킷추가, 링크추가 버튼이 기존에 디자인시스템과 살짝 다른 것 같습니다. 
hPadding이 16이던데 현재 적용한 수치는 작성해주신 버튼의 열거형을 토대로 작업해서 피그마 상 수치와 다릅니다. 디자이너분들과 상의필요..
close #156

fix: 1.0.5 버전에 따른 UI 수정 및 기능 추가

---

Projects/App/Resources/Pokit-info.plist
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/DSKit/Sources/Components/PokitCaution.swift
Projects/DSKit/Sources/Components/PokitList.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
Projects/Feature/FeatureCategorySharing/Sources/CategorySharing/CategorySharingView.swift
Projects/Feature/FeatureContentList/Sources/ContentList/ContentListView.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindView.swift
Projects/Feature/FeatureSetting/Sources/Alert/PokitAlertBoxView.swift
Projects/Feature/FeatureSetting/Sources/Search/PokitSearchView.swift

- 포킷 화면에서 카테고리가 없을 시 Empty화면에서 카테고리 추가 버튼 추가 및 화면 이동 
- 포킷 화면에서 미분류 링크가 없을 시 Empty화면에서 링크 추가 버튼 추가 및 화면 이동 
- 검색 화면 placeholder 수정
- PokitCaution 생성자 열거형 migration
* release 1.0.4 by @stealmh in

release 1.0.5

---

Projects/App/ShareExtension/Sources/ShareRootFeature.swift
Projects/App/Sources/AppDelegate/AppDelegateFeature.swift
Projects/App/Sources/MainTab/MainTabFeature.swift
Projects/App/Sources/MainTab/MainTabPath.swift
Projects/CoreKit/Sources/CoreNetwork/TokenInterceptor.swift
Projects/CoreKit/Sources/Data/Client/KakaoSDK/Share/KakaoShareClient+LiveKey.swift
Projects/CoreKit/Sources/Data/Client/SocialLogin/Controller/AppleLoginController.swift
Projects/DSKit/Sources/Components/PokitBadge.swift
Projects/DSKit/Sources/Components/PokitCalendar.swift
Projects/DSKit/Sources/Components/PokitLinkCard.swift
Projects/DSKit/Sources/Components/PokitLinkPreview.swift
Projects/DSKit/Sources/Components/PokitList.swift
Projects/DSKit/Sources/Components/PokitListButton.swift
Projects/DSKit/Sources/Components/PokitSelect.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailFeature.swift
Projects/Feature/FeatureContentDetail/Sources/ContentDetail/ContentDetailView.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingView.swift
Projects/Feature/FeaturePokit/Sources/PokitRootFeature.swift
Projects/Feature/FeaturePokit/Sources/PokitRootView.swift
Projects/Feature/FeatureRemind/Sources/Remind/RemindFeature.swift
Projects/Feature/FeatureSetting/Sources/Alert/PokitAlertBoxFeature.swift
Projects/Feature/FeatureSetting/Sources/Search/PokitSearchFeature.swift

#167 
- 미분류 페이지에서 컨텐츠가 비어있을 경우 정렬버튼 숨기기
- 링크 추가 페이지에서 링크 텍스트 지우기 버튼 눌렀을 때 제목도 함께 지우기
- 링크 추가 페이지에서 리마인드 선택 영역 삭제
- 링크 저장 완료 팝업 눌렀을 시에 해당 링크의 포킷(미분류) 페이지로 이동
-  메모 수정 시 키보드 툴바(취소, 완료 버튼) 추가
- 링크 추가 페이지에서 텍스트 필드 placeholder 문구 수정
- 포킷 선택 바텀 시트 디자인 수정
- 링크 미리보기에서 스켈레톤에 그림자 제거
- 'PokitLinkCard' 디자인 변경 사항 반영
-  컨텐츠 상세 페이지에서 포킷명 뱃지 위치 수정
- 'PokitListButton' 디자인 수정
--- | --- | ---
>
```Swift
case let .카테고리상세_이동(category):
if category.categoryName == "미분류" {
state.selectedTab = .pokit
state.path.removeAll()
return .send(.pokit(.delegate(.미분류_카테고리_활성화)))
}
state.path.append(.카테고리상세(.init(category: category)))
return .none
```
- 링크 저장 팝업 클릭 시 알맞는 포킷 페이지로 이동하기 위해 미분류 포킷과 일반 포킷을 …

feat: 1.0.6베타 QA 반영

---

Projects/App/Sources/MainTab/MainTabPath.swift
Projects/DSKit/Sources/Components/PokitBottomSheet.swift
Projects/DSKit/Sources/Components/PokitCaution.swift
Projects/DSKit/Sources/Modifiers/PokitFloatButtonModifier.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailFeature.swift
Projects/Feature/FeatureCategoryDetail/Sources/CategoryDetailView.swift
Projects/Feature/FeatureContentSetting/Sources/ContentSetting/ContentSettingFeature.swift

#183 
2.0버전의 포킷 상세화면 작업을 했습니다.
기능적인 구현보다 디자인적 요소가 많았던 작업입니다. 
- 카테고리 내 링크가 없을 때 화면 분기 추가
- 링크추가하기 float button
- 즐겨찾기 상세화면
- 이 외 기능 위치 수정
- 필터링 다중 선택 가능하게끔 수정
| <img src="https://github.com/user-attachments/assets/d0af3953-5b49-4ed7-80df-dcc3c84cb99b" width="200"> | <img src="https://github.com/user-attachments/assets/2ba7d9e2-b62f-479c-b142-111b77e470f7" width="200"> | 
|:-:|:-:|
|`즐겨찾기 상세` | `카테고리 상세` |
>
로직상 문제는 없지만 2.0버전을 준비하면서 몇몇 API가 작동하지 않는 것을 확인했습니다. 또한 겹치는 API도 여럿 있는 상태고 하나하나 잡다가 더 지연될 것 같아서요.
ex) 즐겨찾기 컨텐츠 목록을 조회하기 위해 카테고리 내 컨텐츠 목록 조회를 사용해야 할까..?, 아니면 즐겨찾기 링크 모음 조회를 사용해야할까..?
(두 API의 response가 동일하기 때문에 ... 즐겨찾기 카테고리 목록을 굳이 뽑아써야 할까? 라는 의문이 들어서 내 컨텐츠 목록조회로 즐겨찾기 …

feat: [2.0.0] 버전 업데이트에 따른 기능 추가 및 수정(카테고리 상세)

---

Projects/App/Sources/MainTab/MainTabPath.swift
Projects/DSKit/Sources/Foundation/PokitButtonStyle.swift
Projects/DSKit/Sources/Foundation/PokitImage.swift
Projects/Domain/Sources/Recommend/Recommend.swift
Projects/Feature/FeatureCategorySetting/Sources/PokitCategorySettingView.swift
Projects/Feature/FeatureRecommend/Sources/Recommend/RecommendFeature.swift
Projects/Feature/FeatureRecommend/Sources/Recommend/RecommendView.swift
Projects/Feature/FeatureSetting/Sources/Search/PokitSearchView.swift

> ex) #이슈번호, #이슈번호
#193 
- 썸네일 아이콘 컬러 수정
- +아이콘 수정
- 페이지 배경색 수정
- +버튼 눌렀을 때 플로우 수정
- 전체보기 선택 / 개별 태그 선택 로직 수정
- 카테고리 목록 조회 API 로직을 들고와서 살짝 수정했는데 확인 부탁드려여~
close #193

fix: 2.0.0 QA [2]
